name: Build XO Lite

on:
  push:
    branches: ["dev/hydron/PRNEPHORA-20_Customizes_XO_Lite"]
    # branches: [ "release/hydron" ]
    # tags: [ "hydron-*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'

      - name: Set variables
        run: |
          VERSION=${GITHUB_REF##*/}
          TIMESTAMP=$(date +%s)
          TARBALL=/tmp/xo-lite_${TIMESTAMP}/xo-lite_${VERSION}.tar.gz
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "TARBALL=${TARBALL}" >> $GITHUB_ENV

      - name: Build XO dependencies
        run: yarn

      - name: Build XO Lite dependencies
        run: yarn build:xo-lite

      - name: Build XO Lite
        run: yarn vite build --base=/ --outDir dist
        working-directory: '@xen-orchestra/lite'

      - name: Add license
        run: cp scripts/agpl-3.0.txt dist/LICENSE
        working-directory: '@xen-orchestra/lite'

      - name: Generate tarball
        run: tar -c -z -f ${{ env.TARBALL }} --transform='s|^dist|xo-lite_${{ env.VERSION }}|' dist
        working-directory: '@xen-orchestra/lite'

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: xo-lite_${{ env.VERSION }}
          release_name: xo-lite_${{ env.VERSION }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.TARBALL }}
          asset_name: xo-lite_${{ env.VERSION }}.tar.gz
          asset_content_type: application/gzip
